name: Create and publish a package
on:
  push:
    branches: [ master ]
jobs:
  publish-package-on-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkkout Files
        uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101'
          source-url: https://nuget.pkg.github.com/NickGalazzo/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}   
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Package
        run: dotnet pack --configuration Release
      - name: Publish
        run: dotnet nuget push bin/Release/${{ github.event.repository.name }}.*.nupkg 
